### ISSUE TITLE
NoteJs引入flv.js就报错

### ISSUE THREAD

**Issue by luobobaicaijiazu** [Bilibili/flv.js#143]
这是引入代码：module.exports = require('flv.js');
以下是错误，就算我屏蔽了者几行，又会报其它地方错误，这个是什么问题：
E:\nodejs\app\node_modules\flv.js\dist\flv.js:11357
            if (typeof self.Promise !== 'function') {
                       ^

ReferenceError: self is not defined
    at Function.install (E:\nodejs\app\node_modules\flv.js\dist\flv.js:11357:24)

    at Object.43.es6-promise (E:\nodejs\app\node_modules\flv.js\dist\flv.js:1136
6:10)
    at s (E:\nodejs\app\node_modules\flv.js\dist\flv.js:1:681)
    at E:\nodejs\app\node_modules\flv.js\dist\flv.js:1:732
    at Object.20../core/features.js (E:\nodejs\app\node_modules\flv.js\dist\flv.
js:5781:17)
    at s (E:\nodejs\app\node_modules\flv.js\dist\flv.js:1:681)
    at E:\nodejs\app\node_modules\flv.js\dist\flv.js:1:732
    at Object.21../flv.js (E:\nodejs\app\node_modules\flv.js\dist\flv.js:5875:18
)
    at s (E:\nodejs\app\node_modules\flv.js\dist\flv.js:1:681)
    at e (E:\nodejs\app\node_modules\flv.js\dist\flv.js:1:852)

**Comment by xqq** [comment]
flv.js是前端库，不是给node跑的啊

**Comment by luobobaicaijiazu** [comment]
一直以为是node跑的，现在跑通了。但是我这边出现一个新问题，就是视频跨域的问题，这个现在有没有办法解决？

**Comment by xqq** [comment]
https://github.com/Bilibili/flv.js/blob/master/docs/cors.md

**Comment by luobobaicaijiazu** [comment]
现在是flv文件能在pc上播放，但是不支持iOS和android 上面播放，这是什么情况？

**Comment by xqq** [comment]
善用 issue 搜索

**Comment by luobobaicaijiazu** [comment]
看了下，前面有人说了这个，现在的版本是可以播放只是我没找到点？还是就功能上就不行？

**Comment by Hxmic** [comment]
你这个事怎么解决的了。
我这里也是报错
