### ISSUE TITLE
1.3.0及以上yarn打包错误，不能打包

### ISSUE THREAD

**Issue by HuangWeiping007** [bilibili/flv.js#580]
![1593345807(1)](https://user-images.githubusercontent.com/25784774/85946947-7cd98400-b97a-11ea-9a96-41ec6bbaa322.png)
[Uploading 2020-06-17T12_04_40_075Z-debug.log…]()

**Comment by HuangWeiping007** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @alpha/app-zone@0.0.1~prebuild: @alpha/app-zone@0.0.1
6 info lifecycle @alpha/app-zone@0.0.1~build: @alpha/app-zone@0.0.1
7 verbose lifecycle @alpha/app-zone@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle @alpha/app-zone@0.0.1~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\iot-web-packages\apps\app-zone\node_modules\.bin;C:\Users\ADMINI~1\AppData\Local\Temp\yarn--1592395401894-0.008054839809564784;F:\iot-web-packages\node_modules\.bin;C:\Users\Administrator\AppData\Local\Yarn\Data\link\node_modules\.bin;F:\iot-web-packages\node_modules\.bin;C:\Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Administrator\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs;D:\svn\bin;D:\JDK\java-se-8u40-ri\bin;D:\JDK\java-se-8u40-ri\jre\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\Yarn\bin
9 verbose lifecycle @alpha/app-zone@0.0.1~build: CWD: F:\iot-web-packages\apps\app-zone
10 silly lifecycle @alpha/app-zone@0.0.1~build: Args: [ '/d /s /c', 'alpha-scripts --max_old_space_size=4096 build' ]
11 silly lifecycle @alpha/app-zone@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle @alpha/app-zone@0.0.1~build: Failed to exec build script
13 verbose stack Error: @alpha/app-zone@0.0.1 build: `alpha-scripts --max_old_space_size=4096 build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @alpha/app-zone@0.0.1
15 verbose cwd F:\iot-web-packages\apps\app-zone
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error @alpha/app-zone@0.0.1 build: `alpha-scripts --max_old_space_size=4096 build`
22 error Exit status 1
23 error Failed at the @alpha/app-zone@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
