### ISSUE TITLE
gulp release时无法找到del module？

### ISSUE THREAD

**Issue by ZacksQ** [Bilibili/flv.js#59]
Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Program Files\wamp\www\flv.js-master\gulpfile.js:21:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by xqq** [comment]
npm install 齐了没？

**Comment by ignaciozhuzhu** [comment]
这个报错提示遇到过,npm install装全就好了

**Comment by XiaoyingZhao** [comment]
我下载下来是压缩版的，请问哪里可以下载源码

原始邮件
发件人:ignacionotifications@github.com
收件人:Bilibili/flv.jsflv.js@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2016年12月20日(周二) 14:56
主题:Re: [Bilibili/flv.js] gulp release时无法找到del module？ (#59)


这个报错提示遇到过,npm install装全就好了

**Comment by lianhr12** [comment]
重新安装一下del依赖包，npm install dev

**Comment by lianhr12** [comment]
npm install del

**Comment by bq-hentai27** [comment]
check whether you have install `del` as dev-dep first,
if not, install it.
 `$ npm i del --save-dev`
At last, I don't think this is an issue of flv.js.
