### ISSUE TITLE
[IOController] > Loader error, code = undefined, msg = Cannot read property 'flushStashedSamples' of null flv.min.js:9

### ISSUE THREAD

**Issue by Mactarvish** [bilibili/flv.js#686]
我在linux的nginx服务器上启动了http-flv服务，使用ffmpeg推送摄像头视频流，但是在使用flv.js拉取的时候提示以下错误：
```
[MSEController] > MediaSource onSourceOpen
flv.min.js:9
[IOController] > Loader error, code = undefined, msg = Cannot read property 'flushStashedSamples' of null
flv.min.js:9
[TransmuxingController] > IOException: type = Exception, code = undefined, msg = Cannot read property 'flushStashedSamples' of null
flv.min.js:9
Error: Unhandled error. (undefined)
    at s.emit (file:///E:/mw/flv.min.js:9:10134)
    at s.<anonymous> (file:///E:/mw/flv.min.js:9:90831)
    at s.emit (file:///E:/mw/flv.min.js:9:10268)
    at file:///E:/mw/flv.min.js:9:75417
```

以下是我的拉流代码：
```
        var player = document.getElementById('videoElement');
        if (flvjs.isSupported()) {
            var flvPlayer = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,
                url: 'http://192.168.1.20:8080/live?port=9999&app=myapp&stream=abc'
            });
            flvPlayer.attachMediaElement(videoElement);
            flvPlayer.load(); //加载
            // flv_start();
        }
```

使用ffplay和vlc通过rtmp服务拉流都是成功的，唯独这个基于http的会报错，求指点迷津，谢谢。

**Comment by Mactarvish** [comment]
原因已查明，nginx配置有问题，流没拉出去。

**Comment by xshzh** [comment]
麻烦问下是什么原因，我这也出现这种情况。

**Comment by Mactarvish** [comment]
> 麻烦问下是什么原因，我这也出现这种情况。

检查一下nginx配置看看
